### ISSUE TITLE
关于fasterrcnn tensorrt问题

### ISSUE THREAD

**Issue by wangzhenlin123** [thb1314/tensorrt-onnx-fasterrcnn-fpn-roiailigin#2]
手写ai老哥，这个fasterrcnn tensorrt项目文件有点复杂，请问有独立的工程吗

**Comment by thb1314** [comment]
我不是手写ai老师哈，本项目基于手写ai的https://github.com/shouxieai/tensorRT_cpp，将fasterrcnn onnx生成与部署的全部过程开源。

**Comment by thb1314** [comment]
问题解决
